# Generated by Django 2.2 on 2019-05-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodSwarm', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
