# Generated by Django 2.1.4 on 2019-03-01 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodSwarm', '0004_foodstall_time_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
