# Generated by Django 2.1.4 on 2019-04-02 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FoodSwarm', '0005_remove_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fs_name',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Name of Food Stall'),
        ),
        migrations.AddField(
            model_name='foodstall',
            name='request',
            field=models.CharField(default='YES', max_length=5, verbose_name='Is this a Food Stall Request?'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Updated'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('There are some seats available.', 'There are some seats available.'), ('The Food Stall is full and there are no more seats available.', 'The Food Stall is full and there are no more seats available.'), ("I don't know the current status of the Food Stall.", "I don't know the current status of the Food Stall.")], default="I don't know the current status of the Food Stall.", max_length=100, verbose_name='Current Food Stall Status'),
        ),
        migrations.AlterField(
            model_name='foodstall',
            name='capacity',
            field=models.CharField(default='N/A', max_length=15, verbose_name='Total Capacity'),
        ),
        migrations.AlterField(
            model_name='foodstall',
            name='chairs',
            field=models.CharField(default='N/A', max_length=5, verbose_name='Number of Seats'),
        ),
        migrations.AlterField(
            model_name='foodstall',
            name='description',
            field=models.TextField(default='N/A', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='foodstall',
            name='location',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Location (Address)'),
        ),
        migrations.AlterField(
            model_name='foodstall',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name of Food Stall'),
        ),
        migrations.AlterField(
            model_name='foodstall',
            name='operatinghrs',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Operating Hours'),
        ),
        migrations.AlterField(
            model_name='foodstall',
            name='peakhrs',
            field=models.CharField(default='N/A', max_length=30, verbose_name='Peak Hours'),
        ),
        migrations.AlterField(
            model_name='foodstall',
            name='tables',
            field=models.CharField(default='N/A', max_length=5, verbose_name='Number of Tables'),
        ),
        migrations.AlterField(
            model_name='foodstall',
            name='time_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Created'),
        ),
    ]
